name: xdem-demo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - jupytext
  - numpy=1.26
  - opencv
  - matplotlib
  - rasterio=1.3
  - geopandas=0.14
  - xdem=0.0.17
  - geoutils=0.0.15